import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Send } from "lucide-react";
import { getLocalUser, updateLocalUser, formatTzs } from "@/lib/local-auth";
import { people } from "@/data/people";

export const Route = createFileRoute("/chat")({ validateSearch: (s: Record<string, unknown>) => ({ person: typeof s.person === "string" ? s.person : "Emma" }), head: () => ({ meta: [{ title: "Chat — TALKSWAHILI" }] }), component: ChatPage });
type Msg = { id: string; from: "user" | "foreigner"; text: string; time: string };
const KEY = "talkswahili_chat_";

function ChatPage() {
  const navigate = useNavigate(); const { person: personName } = Route.useSearch();
  const person = useMemo(() => people.find(p => p.name === personName) ?? people[0], [personName]);
  const [text, setText] = useState(""); const [messages, setMessages] = useState<Msg[]>([]); const [gate, setGate] = useState(false);
  useEffect(() => { try { const raw = localStorage.getItem(KEY + person.name); if (raw) setMessages(JSON.parse(raw)); else setMessages([{ id: "welcome", from: "foreigner", text: `Hi! I am ${person.name}. Karibu kwenye chat, unaweza kuanza kuongea nami.`, time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }]); } catch {} }, [person.name]);
  function send(e: React.FormEvent) { e.preventDefault(); const user = getLocalUser(); if (!user) { setGate(true); return; } if (!user.paid) { setGate(true); return; } const clean = text.trim(); if (!clean) return; const now = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); const nextCount = user.messageCount + 1; const mine: Msg = { id: crypto.randomUUID(), from: "user", text: clean, time: now }; const all = [...messages, mine]; setMessages(all); localStorage.setItem(KEY + person.name, JSON.stringify(all)); setText(""); const rewardEvery = 10; if (nextCount % rewardEvery === 0) { const amount = Number((person.pay.match(/[\d,]+/)?.[0] || "0").replace(/,/g, "")); const next = updateLocalUser({ messageCount: nextCount, balance: user.balance + amount }); setTimeout(() => addForeign(`Great! Umefikia ujumbe 10. ${formatTzs(amount)} imeongezwa kwenye balance yako.`), 900); void next; } else { updateLocalUser({ messageCount: nextCount }); setTimeout(() => addForeign(reply(clean)), 900); } }
  function addForeign(text: string) { const m: Msg = { id: crypto.randomUUID(), from: "foreigner", text, time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }; setMessages(prev => { const all = [...prev, m]; localStorage.setItem(KEY + person.name, JSON.stringify(all)); return all; }); }
  return <div className="min-h-screen bg-k-slate-50 font-jost"><header className="sticky top-0 z-10 flex items-center gap-3 border-b border-k-slate-200 bg-white px-4 py-3"><button onClick={() => navigate({ to: "/dashboard" })} className="rounded-xl p-2 hover:bg-k-slate-50"><ArrowLeft className="h-5 w-5" /></button><div className="text-2xl">{person.flag}</div><div><div className="font-bold text-k-slate-900">{person.name}, {person.age}</div><div className="text-xs text-k-green-700">{person.online ? "Online" : "Offline"}</div></div></header>
    <main className="mx-auto flex min-h-[calc(100vh-65px)] max-w-2xl flex-col px-3 py-4"><div className="flex-1 space-y-3 overflow-y-auto pb-4">{messages.map(m => <div key={m.id} className={`flex ${m.from === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm ${m.from === "user" ? "bg-k-indigo text-white" : "border border-k-slate-200 bg-white text-k-slate-800"}`}><div>{m.text}</div><div className={`mt-1 text-[10px] ${m.from === "user" ? "text-white/70" : "text-k-slate-400"}`}>{m.time}</div></div></div>)}</div>
      <form onSubmit={send} className="sticky bottom-2 flex gap-2 rounded-2xl border border-k-slate-200 bg-white p-2 shadow-lg"><input value={text} onChange={e => setText(e.target.value)} placeholder="Andika ujumbe..." className="w-full bg-transparent px-3 text-sm outline-none" /><button className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-k-indigo text-white"><Send className="h-4 w-4" /></button></form></main>
    {gate && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-4 sm:items-center"><div className="w-full max-w-sm rounded-3xl bg-white p-6"><h2 className="text-lg font-extrabold text-k-slate-900">Jisajili ili kuendelea</h2><p className="mt-2 text-sm text-k-slate-500">Unaweza kufungua chat, lakini kutuma ujumbe kunahitaji kujisajili na kukamilisha malipo.</p><button onClick={() => navigate({ to: "/register" })} className="k-btn mt-5">Jisajili Sasa</button><button onClick={() => setGate(false)} className="mt-2 w-full rounded-xl border border-k-slate-200 bg-white px-4 py-3 text-sm font-semibold">Rudi nyuma</button></div></div>}
  </div>;
}
function reply(input: string) { const s = input.toLowerCase(); if (s.includes("hello") || s.includes("hi")) return "Hello! Nice to meet you 😊 What would you like to talk about?"; if (s.includes("habari")) return "I am good, thank you! Na wewe unaendeleaje?"; if (s.includes("jina")) return "My name is your chat partner. Tell me about yourself!"; return "That sounds interesting! Tell me more 😊"; }
