import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowDownToLine, LogOut, MessageCircle, Wallet } from "lucide-react";
import { formatTzs, getLocalUser, updateLocalUser, type LocalUser } from "@/lib/local-auth";
import { people } from "@/data/people";
import logo from "@/assets/talkswahili-logo.png";

export const Route = createFileRoute("/dashboard")({ head: () => ({ meta: [{ title: "Dashboard — TALKSWAHILI" }] }), component: DashboardPage });

function DashboardPage() {
  const navigate = useNavigate();
  const [user, setUser] = useState<LocalUser | null>(null);
  const [amount, setAmount] = useState(""); const [withdrawPhone, setWithdrawPhone] = useState(""); const [error, setError] = useState(""); const [done, setDone] = useState("");
  useEffect(() => { const u = getLocalUser(); if (!u) navigate({ to: "/register" }); else if (!u.paid) navigate({ to: "/payment" }); else { setUser(u); setWithdrawPhone(u.phone); } }, [navigate]);
  function withdraw(e: React.FormEvent) { e.preventDefault(); setError(""); setDone(""); const u = getLocalUser(); const n = Number(amount); if (!u) return navigate({ to: "/register" }); if (n < 50000) return setError("Kiasi cha chini cha withdrawal ni TZS 50,000."); if (n > u.balance) return setError("Salio lako halitoshi."); if (!/^\+?[0-9]{9,15}$/.test(withdrawPhone.replace(/\s/g, ""))) return setError("Namba ya simu si sahihi."); const next = updateLocalUser({ balance: u.balance - n, withdrawn: u.withdrawn + n }); setUser(next); setAmount(""); setDone(`Withdrawal ya ${formatTzs(n)} imewekwa. Salio limepungua.`); }
  if (!user) return <main className="flex min-h-screen items-center justify-center bg-k-slate-50 text-k-slate-500">Inapakia...</main>;
  return <div className="min-h-screen bg-k-slate-50 font-jost text-k-slate-800"><header className="flex items-center justify-between bg-k-green-900 px-4 py-4 sm:px-6"><div className="flex items-center gap-2"><img src={logo} alt="TALKSWAHILI" className="h-9 w-9 rounded-xl object-contain" /><span className="text-lg font-extrabold text-white">TALKSWAHILI</span></div><button onClick={() => { localStorage.removeItem("talkswahili_pending_order"); localStorage.removeItem("talkswahili_payment_reference"); localStorage.removeItem("talkswahili_user"); navigate({ to: "/" }); }} className="flex items-center gap-1 rounded-full bg-white/10 px-4 py-2 text-xs font-semibold text-white"><LogOut className="h-3.5 w-3.5" /> Toka</button></header>
    <main className="mx-auto max-w-3xl px-4 pb-16 pt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-k-slate-900">Karibu, {user.name || user.username}</h1><p className="mt-1 text-sm text-k-slate-500">Akaunti yako imeanzishwa na malipo yamethibitishwa.</p></div><button onClick={() => navigate({ to: "/" })} className="rounded-xl bg-k-indigo px-4 py-2 text-sm font-bold text-white">Chagua Chat</button></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-3"><Stat label="Salio" value={formatTzs(user.balance)} icon={<Wallet className="h-4 w-4" />} /><Stat label="Pesa Iliyotolewa" value={formatTzs(user.withdrawn)} icon={<ArrowDownToLine className="h-4 w-4" />} /><Stat label="Ujumbe" value={String(user.messageCount)} icon={<MessageCircle className="h-4 w-4" />} /></div>
      <section className="mt-8 k-card p-6"><h2 className="font-bold text-k-slate-900">Toa Pesa</h2><p className="mt-1 text-sm text-k-slate-500">Minimum withdrawal ni TZS 50,000.</p><form onSubmit={withdraw} className="mt-5 grid gap-3 sm:grid-cols-2"><input className="k-field" inputMode="numeric" placeholder="Amount" value={amount} onChange={e => setAmount(e.target.value.replace(/\D/g, ""))} /><input className="k-field" inputMode="tel" placeholder="Namba ya simu" value={withdrawPhone} onChange={e => setWithdrawPhone(e.target.value.replace(/[^0-9+]/g, ""))} /><button className="k-btn sm:col-span-2">Toa Pesa</button></form>{error && <p className="mt-3 rounded-xl bg-k-red-50 px-4 py-3 text-sm text-k-red-900">{error}</p>}{done && <p className="mt-3 rounded-xl bg-k-green-100 px-4 py-3 text-sm text-k-green-800">{done}</p>}</section>
      <section className="mt-8 k-card p-6"><h2 className="font-bold text-k-slate-900">Endelea kuchat</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{people.filter(p => p.online).slice(0, 6).map(p => <button key={p.name} onClick={() => navigate({ to: "/chat", search: { person: p.name } })} className="flex items-center justify-between rounded-2xl border border-k-slate-200 bg-white p-4 text-left"><span><span className="block font-bold">{p.flag} {p.name}, {p.age}</span><span className="text-xs text-k-green-700">Online • {p.pay}</span></span><MessageCircle className="h-5 w-5 text-k-indigo" /></button>)}</div></section>
    </main></div>;
}
function Stat({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-2xl border-[1.5px] border-k-slate-200 bg-white px-5 py-4"><div className="flex items-center justify-between text-xs text-k-slate-500"><span>{label}</span><span>{icon}</span></div><div className="mt-1 text-lg font-bold text-k-slate-900">{value}</div></div>; }
